# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chord_pb2 as chord__pb2


class ChordServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/ChordServices/register',
                request_serializer=chord__pb2.register_input.SerializeToString,
                response_deserializer=chord__pb2.register_output.FromString,
                )
        self.deregister = channel.unary_unary(
                '/ChordServices/deregister',
                request_serializer=chord__pb2.deregister_input.SerializeToString,
                response_deserializer=chord__pb2.deregister_output.FromString,
                )
        self.populate_finger_table = channel.unary_unary(
                '/ChordServices/populate_finger_table',
                request_serializer=chord__pb2.pft_input.SerializeToString,
                response_deserializer=chord__pb2.pft_output.FromString,
                )
        self.get_chord_info = channel.unary_unary(
                '/ChordServices/get_chord_info',
                request_serializer=chord__pb2.gci_input.SerializeToString,
                response_deserializer=chord__pb2.gci_output.FromString,
                )
        self.save = channel.unary_unary(
                '/ChordServices/save',
                request_serializer=chord__pb2.save_input.SerializeToString,
                response_deserializer=chord__pb2.save_output.FromString,
                )
        self.remove = channel.unary_unary(
                '/ChordServices/remove',
                request_serializer=chord__pb2.remove_input.SerializeToString,
                response_deserializer=chord__pb2.remove_output.FromString,
                )
        self.find = channel.unary_unary(
                '/ChordServices/find',
                request_serializer=chord__pb2.find_input.SerializeToString,
                response_deserializer=chord__pb2.find_output.FromString,
                )
        self.deligate_ids = channel.unary_unary(
                '/ChordServices/deligate_ids',
                request_serializer=chord__pb2.deligate_input.SerializeToString,
                response_deserializer=chord__pb2.deligate_output.FromString,
                )
        self.connection_type = channel.unary_unary(
                '/ChordServices/connection_type',
                request_serializer=chord__pb2.connection_type_input.SerializeToString,
                response_deserializer=chord__pb2.connection_type_output.FromString,
                )
        self.get_finger_table = channel.unary_unary(
                '/ChordServices/get_finger_table',
                request_serializer=chord__pb2.gft_input.SerializeToString,
                response_deserializer=chord__pb2.gft_output.FromString,
                )


class ChordServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def populate_finger_table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_chord_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deligate_ids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def connection_type(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_finger_table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChordServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=chord__pb2.register_input.FromString,
                    response_serializer=chord__pb2.register_output.SerializeToString,
            ),
            'deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.deregister,
                    request_deserializer=chord__pb2.deregister_input.FromString,
                    response_serializer=chord__pb2.deregister_output.SerializeToString,
            ),
            'populate_finger_table': grpc.unary_unary_rpc_method_handler(
                    servicer.populate_finger_table,
                    request_deserializer=chord__pb2.pft_input.FromString,
                    response_serializer=chord__pb2.pft_output.SerializeToString,
            ),
            'get_chord_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_chord_info,
                    request_deserializer=chord__pb2.gci_input.FromString,
                    response_serializer=chord__pb2.gci_output.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=chord__pb2.save_input.FromString,
                    response_serializer=chord__pb2.save_output.SerializeToString,
            ),
            'remove': grpc.unary_unary_rpc_method_handler(
                    servicer.remove,
                    request_deserializer=chord__pb2.remove_input.FromString,
                    response_serializer=chord__pb2.remove_output.SerializeToString,
            ),
            'find': grpc.unary_unary_rpc_method_handler(
                    servicer.find,
                    request_deserializer=chord__pb2.find_input.FromString,
                    response_serializer=chord__pb2.find_output.SerializeToString,
            ),
            'deligate_ids': grpc.unary_unary_rpc_method_handler(
                    servicer.deligate_ids,
                    request_deserializer=chord__pb2.deligate_input.FromString,
                    response_serializer=chord__pb2.deligate_output.SerializeToString,
            ),
            'connection_type': grpc.unary_unary_rpc_method_handler(
                    servicer.connection_type,
                    request_deserializer=chord__pb2.connection_type_input.FromString,
                    response_serializer=chord__pb2.connection_type_output.SerializeToString,
            ),
            'get_finger_table': grpc.unary_unary_rpc_method_handler(
                    servicer.get_finger_table,
                    request_deserializer=chord__pb2.gft_input.FromString,
                    response_serializer=chord__pb2.gft_output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChordServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChordServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/register',
            chord__pb2.register_input.SerializeToString,
            chord__pb2.register_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/deregister',
            chord__pb2.deregister_input.SerializeToString,
            chord__pb2.deregister_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def populate_finger_table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/populate_finger_table',
            chord__pb2.pft_input.SerializeToString,
            chord__pb2.pft_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_chord_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/get_chord_info',
            chord__pb2.gci_input.SerializeToString,
            chord__pb2.gci_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/save',
            chord__pb2.save_input.SerializeToString,
            chord__pb2.save_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/remove',
            chord__pb2.remove_input.SerializeToString,
            chord__pb2.remove_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/find',
            chord__pb2.find_input.SerializeToString,
            chord__pb2.find_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deligate_ids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/deligate_ids',
            chord__pb2.deligate_input.SerializeToString,
            chord__pb2.deligate_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def connection_type(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/connection_type',
            chord__pb2.connection_type_input.SerializeToString,
            chord__pb2.connection_type_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_finger_table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChordServices/get_finger_table',
            chord__pb2.gft_input.SerializeToString,
            chord__pb2.gft_output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
